import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ActiveLink } from '@/components/atoms/ActiveLink';

const inter = Inter({
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<>
			<html lang="en">
				<body className={inter.className}>
					<nav className="flex space-x-4">
						<ActiveLink href="/products">Products</ActiveLink>

						<ActiveLink href="/">Home</ActiveLink>
					</nav>
					{children}
				</body>
			</html>
		</>
	);
}
